### ISSUE TITLE
problem white crossmobile compile

### ISSUE THREAD

**Issue by beyons** [crossmob/CrossMobile#10]
Hi when i compile crossmobile i have this error
i don't understand the problem

![image](https://user-images.githubusercontent.com/69459996/202182511-453e0ca4-eb81-4ff7-a395-85303e984cfe.png)

**Comment by teras** [comment]
Hello.

You need a Unix machine (either Linux or macOS) in order to compile CerossMobile by yourself.

Actually this is a good suggestion: to fail early with an error message describing this requirement.

**Comment by teras** [comment]
Resolved with https://github.com/crossmob/CrossMobile/commit/4eb8d9de34d15d5e32957139b597d33899b370f6
